### ISSUE TITLE
Depression

### ISSUE THREAD

**Issue by katarinarankovic** [katarinarankovic/Anomaline#9]
She spends a few days in the basement alleviated from depression. Depression comes from hopelessness of saving the dog, hologram and boat.

**Comment by Hilary325** [comment]
I know what depression is from my own experience. My doctor prescribed me antidepressants, but I felt sleepy when taking them (I checked the info about them on the Canadian Pharmacy site, it turned out to be one of the side effects). So, I decided to look for alternative ways. You know, a new hobby helped me. Also, I'm happy to have great friends who support me.
